use dql;
select * from employees;
select firstname, officecode from employees where firstname='Mary';
select firstname, officecode from employees where officecode=1;
select firstname, officecode from employees where officecode=(select officecode from employees where firstname='Mary');
select * from customers;
select customername, country from customers where customername='fungiftideas.com';
select customername, country from customers where country='USA';
select customername, country from customers where country=(select country from customers where customername='fungiftideas.com');
select customername, creditlimit from customers where creditlimit>(select avg(creditlimit) from customers);
select customername, creditlimit from customers where creditlimit=(select max(creditlimit) from customers);
select customername, creditlimit, city from customers where creditlimit>(select max(creditlimit) from customers where city='NYC');
select customername, creditlimit, country from customers where creditlimit in (select max(creditlimit) from customers group by country having country in ('USA','UK','France')); 
select customername, creditlimit, country from customers where creditlimit >any (select max(creditlimit) from customers group by country having country in ('USA','UK','France')); 
select customername, creditlimit, country from customers where creditlimit <any (select max(creditlimit) from customers group by country having country in ('USA','UK','France')); 
select customername, creditlimit, country from customers where creditlimit >all (select max(creditlimit) from customers group by country having country in ('USA','UK','France')); 
select customername, creditlimit, country from customers where creditlimit <all (select max(creditlimit) from customers group by country having country in ('USA','UK','France')); 
select customername, creditlimit, country from customers where creditlimit >all (select avg(creditlimit) from customers group by country having country in ('germany','France'));
select country, avg(creditlimit) from customers group by country having country in ('germany','France');
select customername, creditlimit, country from customers where creditlimit >any (select avg(creditlimit) from customers group by country having country in ('germany','France'));
select customername, creditlimit, country from customers where creditlimit <all (select avg(creditlimit) from customers group by country having country in ('germany','France'));
select * from products;
select productname, productvendor, productline from products where productline in (select productline from products where productline='Planes');
select productname, productline from products where productline='Planes';
select productname, MSRP, productline from products where MSRP<all(select MSRP from products group by productline having productline in ('motorcycles'));
select MSRP from products where productline='motocycles';
select productname, productvendor, productline from products where productvendor in (select productvendor from products where productline ='Planes');
select productname, MSRP, productline from products where MSRP<all(select MSRP from products where productline='motorcycles');
select MSRP from products where productline='motorcycles';
select * from customers;
select firstname, jobtitle, officecode from employees where (jobtitle, officecode)=(select jobtitle, officecode from employees where firstname='pamela');
select customername,country,salesrepemployeenumber from customers where (country, salesrepemployeenumber)=(select country, salesrepemployeenumber from customers where customername='Atelier graphique');
create table empnew(Name varchar(20), officecode int, jobtitle varchar(20));
insert into empnew select firstname, officecode, jobtitle from employees;
select * from empnew;
create table customer1(customername varchar(25), creditlimit decimal(9,2), customernumber int, country varchar(25));
insert into customer1 select customername, creditlimit, customernumber, country from customers;
select* from products;
create table uscustomers as select customername, country, creditlimit from customers where country ='USA';
select * from uscustomers;
drop table uscustomers;
create table classic_cars as select productname, productline, MSRP from products where productline='Classic Cars';
select * from classic_cars;
drop table classic_cars;
set sql_safe_updates=0;
update customers set creditlimit=creditlimit+1000 where city=(select city from customers where customername='FunGiftideas.com');
select * from customers where city = 'New Bedford';
update customers set creditlimit=creditlimit+1000 where country=(select country from customers where customername='FunGiftideas.com');
select * from customers where country = 'USA';